package com.example.christmasapp

import android.content.Intent
import android.os.Bundle
import android.widget.ImageButton
import androidx.appcompat.app.AppCompatActivity


class WelcomePage : AppCompatActivity() {

    val christmasGreetings = arrayOf(
        "Merry Christmas and joy!",
        "Peace, love, and twinkle lights.",
        "Season's blessings to you.",
        "Warm cocoa, warmer hearts!",
        "Snowy wishes, merry kisses.",
        "Let it snow happiness!",
        "Magic and joy await!",
        "Hope shines this season.",
        "Cozy up, it’s Christmas!",
        "Cheers to holiday love.",
        "Twinkling stars, glowing hearts.",
        "Festive cheers, merry years!",
        "Santa’s sleigh is near!",
        "Joyful times, festive rhymes.",
        "Holly, jolly, and bright!",
        "Under the mistletoe glow.",
        "Candles flicker, hearts warm.",
        "A season of sparkling joy.",
        "Reindeer magic fills the air.",
        "Snowflakes and merry dreams.",
        "Gingerbread hugs and love.",
        "Santa's on his way!",
        "All is calm, all is bright.",
        "Believe in the holiday magic.",
        "Pine-scented wishes for you.",
        "Christmas cheer everywhere!",
        "Holiday hugs, festive mugs.",
        "Carols sung with pure joy.",
        "Shimmering lights, warm nights.",
        "Bells ringing, hearts singing.",
        "Unwrap joy this season!",
        "Sparkles, laughter, and love.",
        "Jingle bells and happy spells.",
        "Joy to the world, always!",
        "Bright stars, brighter hearts.",
        "Let Christmas cheer fill you!",
        "Candy canes and snowy lanes.",
        "Fa-la-la-la-la, it’s Christmas!",
        "Wishing you tidings of joy.",
        "Santa’s list has you on it!",
        "Reindeer footprints in snow.",
        "The season of warm hearts.",
        "Happy hearts, holiday starts.",
        "Glow with the Christmas spirit.",
        "Sweet treats, sweeter moments.",
        "Gifts wrapped in love.",
        "Let your heart feel merry.",
        "Frosty mornings, cozy evenings.",
        "Toasty hearts, festive starts.",
        "Wishing you endless wonder.",
        "Stars twinkle, hearts sprinkle.",
        "Crisp air, warm wishes.",
        "Joy sparkles everywhere!",
        "Christmas trees and warm teas.",
        "Snow-dusted magical days.",
        "Mistletoe, kisses, and cheer.",
        "Hugs, smiles, and holiday miles.",
        "Merry hearts, bright starts.",
        "Jolly vibes and glowing tides.",
        "Elves are hard at work!",
        "Presents, peace, and perfection.",
        "Holiday magic is here!",
        "Laughter and light abound.",
        "Share love this holiday season.",
        "Ornaments glow with cheer.",
        "Frosty fun, holiday sun.",
        "Baking cookies, spreading joy.",
        "Seasonal greetings from the heart.",
        "Deck the halls with joy!",
        "Silent nights, joyful sights.",
        "Yule magic is everywhere.",
        "Wrapping joy in every bow.",
        "Evergreen trees and happy bees.",
        "Festive spirit, warmest hugs.",
        "Wishing you frosty delight.",
        "Holiday warmth fills the air.",
        "Golden bells and snowy spells.",
        "Stars and stockings, all bright.",
        "Holiday hugs for everyone.",
        "Decked out in Christmas cheer.",
        "Rejoice in holiday splendor!",
        "Heartfelt greetings, festive meetings.",
        "Cheer abounds, magic surrounds.",
        "Dreams of snow and joy.",
        "Happy wishes, festive dishes.",
        "Cider, warmth, and celebration.",
        "Bright memories for you.",
        "Season’s greetings, warm meetings.",
        "May your holidays glow bright.",
        "Winter magic and bright stars.",
        "Sharing joy and heartfelt love.",
        "Wishing snowflakes and joy.",
        "Christmas cuddles and carols."
    )
    val giftIdeas = arrayOf(
        "LEGO set",
        "Cozy socks",
        "Bluetooth headphones",
        "Gift card",
        "Board game",
        "Scented candles",
        "Plush blanket",
        "Fitness tracker",
        "Smartphone stand",
        "Cookbook",
        "Coffee mug",
        "Portable speaker",
        "Wireless earbuds",
        "Chocolate gift box",
        "Puzzle set",
        "Stationery set",
        "Instant camera",
        "Art supplies",
        "Perfume or cologne",
        "Wool scarf",
        "Slippers",
        "Backpack",
        "Tool kit",
        "Pocket knife",
        "Electric toothbrush",
        "Portable charger",
        "Succulent plant",
        "Jewelry",
        "Luxury pen",
        "Yoga mat",
        "Subscription box",
        "Custom photo frame",
        "Cooking utensils",
        "Knit hat",
        "Car phone mount",
        "Leather wallet",
        "Water bottle",
        "Smartwatch",
        "Book set",
        "Gaming controller",
        "VR headset",
        "Portable coffee maker",
        "Hair styling tools",
        "Beanie",
        "Hoodie",
        "Wine glasses",
        "Skincare set",
        "Makeup palette",
        "Outdoor camping gear",
        "Travel pillow",
        "Noise-canceling headphones",
        "Mini projector",
        "Robot vacuum",
        "Slime making kit",
        "Karaoke microphone",
        "Telescope",
        "Subscription to a streaming service",
        "Pet toys",
        "Gourmet snacks basket",
        "Hot chocolate set",
        "Bicycle accessories",
        "Jigsaw puzzles",
        "Retro video games",
        "Desk organizer",
        "Smart home device",
        "Bath bomb set",
        "Notebook journal",
        "Stylish sunglasses",
        "Cooking spices set",
        "Custom puzzle with a photo",
        "Personalized keychain",
        "Luxury bathrobe",
        "Bean bag chair",
        "Digital picture frame",
        "DIY craft kit",
        "Musical instrument",
        "E-book reader",
        "Popcorn maker",
        "Wireless gaming mouse",
        "Sports equipment",
        "Travel organizer",
        "Gaming headset",
        "Car emergency kit",
        "Electric scooter",
        "VR gaming headset",
        "Massage gun",
        "Reusable shopping bags",
        "Indoor plant kit",
        "Electric blanket",
        "Portable smoothie blender",
        "Solar-powered charger",
        "Designer watch",
        "Custom jewelry box",
        "Mini drone",
        "Wine opener set",
        "Luxury pillow",
        "Educational science kit"
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_welcome_page)

       val giftButton = findViewById<ImageButton>(R.id.GiftButton)
            giftButton.setOnClickListener {

            val intent = Intent(this, GiftActivity::class.java)
            startActivity(intent)
            }

       val greetingButton = findViewById<ImageButton>(R.id.GreetingButton)
        greetingButton.setOnClickListener {

            val intent = Intent(this, GreetingActivity::class.java)
            startActivity(intent)
        }

        val viewHistoryButton = findViewById<ImageButton>(R.id.ViewHistoryButton)
        viewHistoryButton.setOnClickListener {

            val intent = Intent(this, HistoryActivity::class.java)
            startActivity(intent)
        }
}}